name: eatanytime
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.4.0
  geolocator: ^6.1.14
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/food.jpg
    - images/burger.jpg
    - images/sandwitch.jpg
    - images/pizza.jpg
    - images/splash.png
  #   - images/a_dot_ham.jpeg


flutter_native_splash:
  image: images/splash.png
  color: "42a5f5"